# Generated by Django 5.0.6 on 2024-06-09 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='photo_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
